[2024-12-23T13:00:44.261+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.linear_regression manual__2024-12-23T12:59:31.443237+00:00 [queued]>
[2024-12-23T13:00:44.267+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.linear_regression manual__2024-12-23T12:59:31.443237+00:00 [queued]>
[2024-12-23T13:00:44.268+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2024-12-23T13:00:44.277+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): linear_regression> on 2024-12-23 12:59:31.443237+00:00
[2024-12-23T13:00:44.286+0000] {standard_task_runner.py:60} INFO - Started process 13930 to run task
[2024-12-23T13:00:44.290+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'linear_regression', 'manual__2024-12-23T12:59:31.443237+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmp92uzrhri']
[2024-12-23T13:00:44.291+0000] {standard_task_runner.py:88} INFO - Job 257: Subtask linear_regression
[2024-12-23T13:00:44.305+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-23T13:00:44.327+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.linear_regression manual__2024-12-23T12:59:31.443237+00:00 [running]> on host b853fb0270cd
[2024-12-23T13:00:44.384+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='linear_regression' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T12:59:31.443237+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T12:59:31.443237+00:00'
[2024-12-23T13:00:44.419+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract.py", line 142, in Linear_Regression_Model
    feats =data.drop(["target", "city"], axis = 1)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 5258, in drop
    return super().drop(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 4549, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 4591, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6699, in drop
    raise KeyError(f"{list(labels[mask])} not found in axis")
KeyError: "['city'] not found in axis"
[2024-12-23T13:00:44.431+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=linear_regression, execution_date=20241223T125931, start_date=20241223T130044, end_date=20241223T130044
[2024-12-23T13:00:44.442+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 257 for task linear_regression ("['city'] not found in axis"; 13930)
[2024-12-23T13:00:44.460+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-23T13:00:44.477+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
